### ISSUE TITLE
Author page link issue

### ISSUE THREAD

**Issue by SeanKilleen** [RyKilleen/rykilleen.github.io#12]
Repro:

* Go to your author page: http://www.ryankilleen.com/author/ryan/
* Click web site link or picture of your face

Expected behavior: Go to same web site again

Actual behavior: Browser attempts to go to `http://www.ryankilleen.com/https://www.ryankilleen.com/` and finds a not found page instead.

**Comment by RyKilleen** [comment]
Good catch, thanks!
